# Change these first
owner: shawncsmedgas # Your GitHub organization or username, where this repository lives
repo: upptime-csmedgas # The name of this repository

sites:
  - name: Homepage
    url: https://csmedgas.com/
    maxResponseTime: 5000
  - name: Contact Page
    url: https://csmedgas.com/contact/
    maxResponseTime: 5000
  - name: Sitemap
    url: https://csmedgas.com/sitemap_index.xml

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime-csmedgas
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: csmedgas.com Uptime Status by Upptime
  introTitle: "**csmedgas.com** Uptime Monitor powered by Upptime & GitHub"
  introMessage: This repo has been adapted for use by Compliance Solutions LLC to report the uptime status of the primary website.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
